services:
  postgres16:
    image: postgres:16
    container_name: postgres16
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: be_main_module
    volumes:
      - postgres16-data:/var/lib/postgresql/data

volumes:
  postgres16-data:
